export const normalizeEmojiSearchValue = (value = '') => value
  .toLowerCase()
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '');

export const emojiCategoryOptions = [
  { id: 'RECENT', label: 'Récents', icon: '🕘' },
  { id: 'ALL', label: 'Tous', icon: '🔎' },
  { id: 'SMILEYS', label: 'Smileys', icon: '😀' },
  { id: 'HEARTS', label: 'Cœurs', icon: '❤️' },
  { id: 'GESTURES', label: 'Gestes', icon: '👍' },
  { id: 'CELEBRATION', label: 'Fête', icon: '🎉' },
  { id: 'NATURE', label: 'Nature', icon: '🌈' },
  { id: 'FOOD', label: 'Nourriture', icon: '🍕' },
  { id: 'ACTIVITIES', label: 'Activités', icon: '⚽' },
  { id: 'OBJECTS', label: 'Objets', icon: '💼' }
];

const includesAnyToken = (searchTokens, tokens) => tokens.some(token => searchTokens.includes(token));

const inferEmojiCategory = (searchTokens) => {
  if (includesAnyToken(searchTokens, ['heart', 'coeur', 'coeurs', 'amour', 'love', 'liefde', 'herz', 'corazon'])) {
    return 'HEARTS';
  }

  if (includesAnyToken(searchTokens, ['hand', 'mains', 'main', 'thumb', 'gesture', 'wave', 'clap', 'pray', 'doigts', 'fingers'])) {
    return 'GESTURES';
  }

  if (includesAnyToken(searchTokens, ['party', 'fete', 'celebration', 'confetti', 'victory', 'fiesta', 'feest'])) {
    return 'CELEBRATION';
  }

  if (includesAnyToken(searchTokens, ['sun', 'moon', 'rainbow', 'snow', 'fire', 'star', 'nature', 'soleil', 'lune', 'regenboog'])) {
    return 'NATURE';
  }

  if (includesAnyToken(searchTokens, ['pizza', 'burger', 'fries', 'apple', 'strawberry', 'cake', 'chocolate', 'coffee', 'nourriture', 'food'])) {
    return 'FOOD';
  }

  if (includesAnyToken(searchTokens, ['football', 'game', 'rocket', 'trophy', 'activite', 'actividades', 'spiel'])) {
    return 'ACTIVITIES';
  }

  if (includesAnyToken(searchTokens, ['briefcase', 'books', 'cart', 'speech', 'bubble', 'objet', 'travail', 'werk', 'arbeit'])) {
    return 'OBJECTS';
  }

  return 'SMILEYS';
};

const rawEmojiCatalog = [
  ['😀', 'grinning smile happy joy sourire content vrolijk blij lachen laecheln alegre feliz'],
  ['😃', 'smile happy grin sourire joyeux blij lachen laecheln sonreir'],
  ['😄', 'laugh smile grin rire sourire lachen lachen sonriendo'],
  ['😁', 'beaming grin smile fierte sourire trots stolz orgullo'],
  ['😆', 'laughing lol rire mdrr lachen lachen reir'],
  ['😅', 'sweat smile ouf soulage opgelucht erleichtert aliviado'],
  ['🤣', 'rofl laugh rire exploser lachen lachen reirse'],
  ['😂', 'joy tears rire larmes tranen lachen traenen risa'],
  ['🙂', 'slight smile doux gentle mild zacht sanft suave'],
  ['😉', 'wink clin oeil knipoog zwinkern guino'],
  ['😊', 'blush shy timide gene verlegen schuechtern timido'],
  ['😇', 'angel innocent saint ange onschuldig engel inocente'],
  ['🥰', 'love hearts amoureux amour liefde herz corazones'],
  ['😍', 'heart eyes love amoureux verliefd verliebt enamorado'],
  ['🤩', 'star eyes wow impressionne indruk beeindruckt asombrado'],
  ['😘', 'kiss bisou baiser kus kuss beso'],
  ['😗', 'kiss simple baiser kus kuss beso'],
  ['😚', 'closed eyes kiss bisou kus kuss beso'],
  ['😙', 'smiling kiss baiser sourire kus kuss beso'],
  ['😋', 'yum delicious miam lekker lecker delicioso'],
  ['😛', 'tongue langue tong zunge lengua'],
  ['😜', 'winking tongue langue knipoog zunge guino'],
  ['🤪', 'crazy goofy fou gek verrueckt loco'],
  ['😝', 'squint tongue langue plisser knijpen zusammenkneifen'],
  ['🤑', 'money rich argent rijk reich rico'],
  ['🤗', 'hug calin knuffel umarmung abrazo'],
  ['🤭', 'oops surprise oups verrast ueberrascht sorpresa'],
  ['🫢', 'gasp choque choc geschokt schockiert sorprendido'],
  ['🤫', 'shh silence chut stil leise silencio'],
  ['🤔', 'thinking pense nadenken denken pensar'],
  ['🫡', 'salute respect salut groet gruss saludo'],
  ['🤐', 'zipper mouth secret geheim secreto'],
  ['🤨', 'skeptical doute sceptique twijfel skeptisch dudoso'],
  ['😐', 'neutral neutre neutraal neutral neutral'],
  ['😑', 'expressionless blase impassible uitdrukkingsloos ausdruckslos inexpresivo'],
  ['😶', 'silent sans voix stil still silencio'],
  ['🫥', 'dotted line disappear invisible invisible unsichtbar invisible'],
  ['😶‍🌫️', 'foggy confus brouillard mist nebel niebla'],
  ['😏', 'smirk sourire en coin grijns grinsen sonrisa'],
  ['😒', 'unamused blase pas content niet blij unzufrieden molesto'],
  ['🙄', 'eye roll lever les yeux ogen rollen augenrollen ojos'],
  ['😬', 'grimace grimace grimace grimasse mueca'],
  ['😮‍💨', 'relief soupir zucht seufzer suspiro'],
  ['🤥', 'lie mensonge leugen luege mentira'],
  ['😌', 'relieved soulage opgelucht erleichtert aliviado'],
  ['😔', 'pensive pensif nadenkend nachdenklich pensativo'],
  ['😪', 'sleepy somnolent slaperig schlaefrig sonoliento'],
  ['🤤', 'drool baver kwijlen sabbern babear'],
  ['😴', 'sleep dormir slapen schlafen dormir'],
  ['😷', 'mask malade ziek krank enfermo'],
  ['🤒', 'fever fievre koorts fieber fiebre'],
  ['🤕', 'hurt blesse gewond verletzt herido'],
  ['🤢', 'nausea nausee misselijk uebel nausea'],
  ['🤮', 'vomit vomir overgeven erbrechen vomitar'],
  ['🤧', 'sneeze eternuer niezen niesen estornudar'],
  ['🥵', 'hot chaud heet heiss calor'],
  ['🥶', 'cold froid koud kalt frio'],
  ['🥴', 'dizzy ivre duizelig schwindlig mareado'],
  ['😵', 'dizzy dead choque duizelig schwindel mareo'],
  ['😵‍💫', 'spiral dizzy tourne duizelig schwindel mareo'],
  ['🤯', 'mind blown explosion explose ontploft explodiert estalla'],
  ['🤠', 'cowboy chapeau western hoed hut sombrero'],
  ['🥳', 'party fete feest party fiesta'],
  ['😎', 'cool lunettes zonnebril sonnenbrille gafas'],
  ['🤓', 'nerd geek intello nerd nerd friki'],
  ['🧐', 'monocle inspect examiner bekijken untersuchen examinar'],
  ['😕', 'confused confus verward verwirrt confundido'],
  ['😟', 'worried inquiet bezorgd besorgt preocupado'],
  ['🙁', 'slight frown triste frons stirnrunzeln triste'],
  ['☹️', 'frown triste frons stirnrunzeln triste'],
  ['😮', 'open mouth surpris verrast ueberrascht sorprendido'],
  ['😯', 'hushed choque choc geschokt schockiert sorprendido'],
  ['😲', 'astonished etonne verbaasd erstaunt asombrado'],
  ['😳', 'flushed gene blozen erroeten rubor'],
  ['🥺', 'pleading s il te plait alsjeblieft bitte porfavor'],
  ['🥹', 'tears emu larmes tranen traenen lagrimas'],
  ['😦', 'frown open triste openen offen triste'],
  ['😧', 'anguished angoisse angst angst angustia'],
  ['😨', 'fear peur bang angst miedo'],
  ['😰', 'anxious sueur stresse zweten angst sudor'],
  ['😥', 'sad but relieved triste opgelucht erleichtert aliviado'],
  ['😢', 'cry pleurer huilen weinen llorar'],
  ['😭', 'sob larmes pleurs tranen weinen llorando'],
  ['😱', 'scream peur cri schreeuw schreien grito'],
  ['😖', 'confounded frustre gefrustreerd frustriert frustrado'],
  ['😣', 'persevere effort moeite muehe esfuerzo'],
  ['😞', 'disappointed decu teleurgesteld enttaeuscht decepcionado'],
  ['😓', 'sweat triste transpire zweten schwitzen sudar'],
  ['😩', 'weary fatigue moe muede cansado'],
  ['😫', 'tired epuise moe muede agotado'],
  ['🥱', 'yawn baille geeuwen gaehnen bostezo'],
  ['😤', 'steam fache enerve boos wuetend furioso'],
  ['😡', 'angry en colere boos wuetend enojado'],
  ['😠', 'mad fache kwaad wutend enfadado'],
  ['🤬', 'swear insult gros mot schelden fluchen insulto'],
  ['😈', 'devil malin duivel teufel diablo'],
  ['👿', 'angry devil diable duivel teufel diablo'],
  ['💀', 'skull mort dood tod muerte'],
  ['☠️', 'skull crossbones danger danger gefahr peligro'],
  ['💩', 'poop caca crotte poep kacke caca'],
  ['🤡', 'clown clown clown clown payaso'],
  ['👻', 'ghost fantome spook geist fantasma'],
  ['👽', 'alien extraterrestre buitenaards alienigena alien'],
  ['🤖', 'robot robot robot roboter robot'],
  ['🎃', 'pumpkin halloween citrouille pompoen kuerbis calabaza'],
  ['😺', 'cat smile chat kat katze gato'],
  ['😸', 'cat laugh chat rire kat lachen katze'],
  ['😹', 'cat tears chat larmes kat tranen katze'],
  ['😻', 'cat heart chat amour kat liefde katze'],
  ['😼', 'cat smirk chat kat grijns katze'],
  ['🙈', 'see no evil singe monkey aap affe mono'],
  ['🙉', 'hear no evil singe monkey aap affe mono'],
  ['🙊', 'speak no evil singe monkey aap affe mono'],
  ['💌', 'love letter lettre amour liefdesbrief liebesbrief carta'],
  ['💘', 'heart arrow amour fleche liefde pijl liebe pfeil'],
  ['💝', 'gift heart cadeau coeur cadeau herz regalo'],
  ['💖', 'sparkle heart coeur brillant glanzend glitzer corazon'],
  ['💗', 'growing heart coeur grandit groeiend wachsend creciendo'],
  ['💓', 'beating heart coeur bat kloppend schlagend latiendo'],
  ['💞', 'revolving hearts coeurs tournants draaiend drehend girando'],
  ['💕', 'two hearts deux coeurs twee herzen dos corazones'],
  ['💟', 'heart decoration deco coeur decoratie verzierung decoracion'],
  ['❣️', 'heart exclamation coeur exclamation ausrufezeichen exclamacion'],
  ['❤️', 'red heart coeur rouge rood herz rojo amor love liefde'],
  ['🧡', 'orange heart coeur orange oranje herz naranja'],
  ['💛', 'yellow heart coeur jaune geel herz amarillo'],
  ['💚', 'green heart coeur vert groen herz verde'],
  ['💙', 'blue heart coeur bleu blauw herz azul'],
  ['💜', 'purple heart coeur violet paars herz morado'],
  ['🤎', 'brown heart coeur marron bruin herz marron'],
  ['🖤', 'black heart coeur noir zwart herz negro'],
  ['🤍', 'white heart coeur blanc wit herz blanco'],
  ['💯', 'hundred cent parfait perfect perfect perfekt perfecto'],
  ['💢', 'anger symbol colere boos wut furia'],
  ['💥', 'boom explosion explosion explosie explosion explosion'],
  ['💫', 'dizzy etoile sterne sterren estrellas'],
  ['💦', 'sweat drops gouttes zweet tropfen gotas'],
  ['💨', 'dash vitesse speed snelheid geschwindigkeit velocidad'],
  ['🕳️', 'hole trou gat loch agujero'],
  ['💬', 'speech bubble parole chat praat sprechen hablar'],
  ['🗨️', 'left speech bubble bulle conversation spreekblase globo'],
  ['🗯️', 'angry bubble bulle colere boze blase wuetende burbuja'],
  ['💭', 'thought bubble pensee gedachte gedanke pensamiento'],
  ['💤', 'zzz sleep dodo slapen schlafen dormir'],
  ['👋', 'wave salut hallo hallo hola'],
  ['🤚', 'raised back hand main hand hand mano'],
  ['🖐️', 'raised hand main hand hand mano'],
  ['✋', 'stop hand arret stop stop alto'],
  ['🫱', 'rightwards hand droite rechts derecha'],
  ['🫲', 'leftwards hand gauche links izquierda'],
  ['🫶', 'heart hands mains coeur handhart haendeherz manos'],
  ['👌', 'ok parfait goed gut bien'],
  ['🤌', 'pinched fingers italien doigts vingers finger dedos'],
  ['🤏', 'pinching hand petit klein klein pequeno'],
  ['✌️', 'victory paix vrede frieden paz'],
  ['🤞', 'crossed fingers chance geluk glueck suerte'],
  ['🫰', 'money fingers coreen geld geld dinero'],
  ['🤟', 'love you hand je taime ikhouvanjou ichliebedich tequiero'],
  ['🤘', 'rock cornes horns hoorns hoerner cuernos'],
  ['🤙', 'call me telephone bel me bellen anrufen llamar'],
  ['👈', 'point left gauche links izquierda'],
  ['👉', 'point right droite rechts derecha'],
  ['👆', 'point up haut omhoog oben arriba'],
  ['👇', 'point down bas omlaag unten abajo'],
  ['👍', 'thumbs up jaime like top goed gut bien'],
  ['👎', 'thumbs down dislike nul slecht schlecht mal'],
  ['👏', 'clap bravo applaud applaud klatschen aplauso'],
  ['🙌', 'raised hands victoire victory handen haende manos'],
  ['👐', 'open hands mains ouvertes open handen offene haende'],
  ['🤲', 'palms up recevoir ontvangen empfangen recibir'],
  ['🙏', 'pray merci svp dank danke porfavor rezar'],
  ['✍️', 'writing ecrire schrijven schreiben escribir'],
  ['💅', 'nails manicure ongles nagels naegel unas'],
  ['💪', 'muscle force kracht staerke fuerza'],
  ['🦾', 'mechanical arm bras robot robotarm roboterarm'],
  ['🧠', 'brain cerveau brein gehirn cerebro'],
  ['🫀', 'heart organ coeur organe hart herz corazon'],
  ['🫁', 'lungs poumons longen lunge pulmones'],
  ['🦷', 'tooth dent tand zahn diente'],
  ['👀', 'eyes yeux ogen augen ojos voir kijken sehen mirar'],
  ['🫂', 'people hugging calin knuffel umarmung abrazo'],
  ['🎉', 'party celebration fete feest feier fiesta'],
  ['🎊', 'confetti celebration confettis feest konfetti fiesta'],
  ['✨', 'sparkles brillant glinsteren funkeln brillo'],
  ['🔥', 'fire feu brand fire fuego'],
  ['⭐', 'star etoile ster stern estrella'],
  ['🌟', 'glowing star etoile brillante schitterend leuchtend brillante'],
  ['🌈', 'rainbow arc en ciel regenboog regenbogen arcoiris'],
  ['☀️', 'sun soleil zon sonne sol'],
  ['🌙', 'moon lune maan mond luna'],
  ['⚡', 'lightning eclair bliksem blitz rayo'],
  ['❄️', 'snow neige sneeuw schnee nieve'],
  ['☕', 'coffee cafe koffie kaffee cafe'],
  ['🍕', 'pizza pizza pizza pizza pizza'],
  ['🍔', 'burger hamburger hamburger hamburger hamburguesa'],
  ['🍟', 'fries frites patat pommes patatas'],
  ['🍎', 'apple pomme appel apfel manzana'],
  ['🍓', 'strawberry fraise aardbei erdbeere fresa'],
  ['🎂', 'cake gateau taart kuchen tarta'],
  ['🍫', 'chocolate chocolat chocolade schokolade chocolate'],
  ['🏆', 'trophy victoire winst sieg trofeo'],
  ['⚽', 'football foot voetbal fussball futbol'],
  ['🎮', 'game jeu spel spiel juego'],
  ['🚀', 'rocket fusee raket rakete cohete'],
  ['💼', 'briefcase travail werk arbeit trabajo'],
  ['📚', 'books livres boeken buecher libros'],
  ['🛒', 'cart shopping achat winkelen einkaufen compras']
];

export const emojiCatalog = rawEmojiCatalog.map(([emoji, keywords]) => ({
  emoji,
  searchTokens: normalizeEmojiSearchValue(keywords),
  category: inferEmojiCategory(normalizeEmojiSearchValue(keywords))
}));
